name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install Deps
      run: npm install && npm i grunt -g
    - name: Tests
      run: grunt